### ISSUE TITLE
[Fav Icon]

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/comment_tree_app#30]
Need to add `fav icon` to the app.

**Comment by FaheemAhmedNoor** [comment]
Hey @ShehrozIrfan !
I would be pleased if you assign this issue to me.

**Comment by ShehrozIrfan** [comment]
Hey @FaheemAhmedNoor,
Assigned.

We need to add this image as `Favicon`:

![favicon](https://user-images.githubusercontent.com/36946330/205428112-58ca8da0-3d4f-4781-8e83-c81809442be3.png)

**Comment by FaheemAhmedNoor** [comment]
I've done this and here is the link of PR. 
https://github.com/ShehrozIrfan/comment_tree_app/pull/47
