### ISSUE TITLE
[Full Name] Show `user` full name

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/comment_tree_app#46]
### Context
- We're using the `first_name` attribute to display the user name right below its comment

### Update
- We want to display the user's full name

### Approach
- We can concatenate the `first_name` and `last_name` and get the user's full name
- Write a method `name` that will return the user's full name after concatenation
- Use the `name` method to display the user full name

**Comment by ArshErgon** [comment]
Hey @ShehrozIrfan can you assign it to me?
its going to be my first contribution in ruby

**Comment by ShehrozIrfan** [comment]
@ArshErgon 
Assigned.
Please do let me know which approach you'll be using to solve this. 
- Creating an instance method?
- Writing a helper method?

**Comment by ArshErgon** [comment]
@ShehrozIrfan you are talking about this file https://github.com/ShehrozIrfan/comment_tree_app/blob/master/app/views/comments/show.html.erb#L23
and well I was thinking when we are filtering out the `first_name` to show the name for the comment, maybe we can make a variable `user_full_name` and assign it to `first_name + last_name` and return `user_full_name` in the template. 
Can we place our variables inside the templates in ruby?

**Comment by ShehrozIrfan** [comment]
@ArshErgon 
This approach can be a solution to this as you explained. But think of some better solutions like having a `helper_method` named `full_name`, that take two arguments `first_name` and `last_name`, and then returns the full name after `concatenation`.

You can follow the rails conventions of using helper methods.

**Comment by ArshErgon** [comment]
well, we are looping [every single](https://github.com/ShehrozIrfan/comment_tree_app/blob/master/app/views/comments/index.html.erb#L9) comment inside the template, as far as I know, its not possible doing a back and forth operation to get the full name of every single comment when we are looping inside the `templates` not in the main ruby file if we are displaying only one comment, then we could filter out the full name as it has done [here](https://github.com/ShehrozIrfan/comment_tree_app/blob/master/app/controllers/comments_controller.rb#L23)
I think as for now, it can be done in two ways
1. Create a new model parameter for full_name which takes (it will take extra memory)
2. or using the thing which we have already, means
like [here](https://github.com/ShehrozIrfan/comment_tree_app/blob/master/app/views/comments/index.html.erb#L13)
you have used `comment&.user&.first_name` we could also add `comment&.user&.last_name`

There must be a better way, you know Ruby better than I do

**Comment by ShehrozIrfan** [comment]
> every single

#### Context
Actually, here we're using `MVC`, the `@comments` is an instance variable that is coming from the `index` action. And in `Rails` there is a convention for using `helpers` and they are available for every `controller`.

#### Issue:
For the approach you mentioned in point `2`, we can use that but we need to add this on every page where we need to show the full name, and it's a repetition.

#### Better Approach:
What we can do is we can write a simple helper method in `comments_helper` and name it to let's say, `get_full_name(first_name, last_name)`.
So, now whenever we need to get the full name, we will call this helper and pass two arguments to it `first_name` and `last_name` and it will give us the full name.
In this way we don't need to concatenate the first name and last name on any page where full name is required, we just call this helper method.

#### Friendly Question:
Do you have any prior knowledge of `Rails`? Don't worry it's a friendly question.

**Comment by ArshErgon** [comment]
No, I don't have any experience with Rails, that's why I mention above 'it's going to be my first contribution in ruby'
A little help from you, I have created the file inside the `helpers`, so now where this function will be called? if we are calling it inside the templates like `<%= get_full_user_name(comment&.user&.first_name, comment&.user&.last_name) %>` we are still doing repetition

**Comment by ShehrozIrfan** [comment]
Ahh, okay.
Then we might need to do it in the `model`.
Let me make some updates and let you know!

**Comment by ShehrozIrfan** [comment]
#49 
Hey @ArshErgon ,
Here I've added the `name` method in the `model` file. And now we just need to use `user.name` and it will return the user's full name.

Now we need to make updates on every file, where the `first_name` is used.

**Comment by ArshErgon** [comment]
okay, so @ShehrozIrfan  I change every occurrence of `first_name` in the templates, the occurrence can be found in `edit.html`, `new.html`, `index.html` and `show.html`, and should we change the `user.name` to something more readable? like `user.username` or `user.full_name`?

**Comment by ShehrozIrfan** [comment]
@ArshErgon 
Yes, we need to make the updates in the files you mentioned.

Well, I think `name` is good. But yeah we can change it to `full_name`, that will be more readable.
