### ISSUE TITLE
Add limit on comment text when it is shown on main page.

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/comment_tree_app#7]
We need to add the limit on comment text, when it is shown on the `index` page. Like limit of only 255 characters. The remaining text will be shown when user clicks on the comment and go to that specific comment page.

**Comment by FaheemAhmedNoor** [comment]
Hey @ShehrozIrfan !
Can you please assign this issue to me.

**Comment by FaheemAhmedNoor** [comment]
I've done with this issue and below is the PR of it can you please merge it after review.
https://github.com/ShehrozIrfan/comment_tree_app/pull/48
